################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../tflm/tensorflow/lite/micro/kernels/activations.cc \
../tflm/tensorflow/lite/micro/kernels/activations_common.cc \
../tflm/tensorflow/lite/micro/kernels/add_common.cc \
../tflm/tensorflow/lite/micro/kernels/add_n.cc \
../tflm/tensorflow/lite/micro/kernels/arg_min_max.cc \
../tflm/tensorflow/lite/micro/kernels/assign_variable.cc \
../tflm/tensorflow/lite/micro/kernels/batch_to_space_nd.cc \
../tflm/tensorflow/lite/micro/kernels/broadcast_args.cc \
../tflm/tensorflow/lite/micro/kernels/broadcast_to.cc \
../tflm/tensorflow/lite/micro/kernels/call_once.cc \
../tflm/tensorflow/lite/micro/kernels/cast.cc \
../tflm/tensorflow/lite/micro/kernels/ceil.cc \
../tflm/tensorflow/lite/micro/kernels/circular_buffer.cc \
../tflm/tensorflow/lite/micro/kernels/circular_buffer_common.cc \
../tflm/tensorflow/lite/micro/kernels/comparisons.cc \
../tflm/tensorflow/lite/micro/kernels/concatenation.cc \
../tflm/tensorflow/lite/micro/kernels/conv_common.cc \
../tflm/tensorflow/lite/micro/kernels/cumsum.cc \
../tflm/tensorflow/lite/micro/kernels/decompress.cc \
../tflm/tensorflow/lite/micro/kernels/decompress_common.cc \
../tflm/tensorflow/lite/micro/kernels/depth_to_space.cc \
../tflm/tensorflow/lite/micro/kernels/depthwise_conv_common.cc \
../tflm/tensorflow/lite/micro/kernels/dequantize.cc \
../tflm/tensorflow/lite/micro/kernels/dequantize_common.cc \
../tflm/tensorflow/lite/micro/kernels/detection_postprocess.cc \
../tflm/tensorflow/lite/micro/kernels/div.cc \
../tflm/tensorflow/lite/micro/kernels/elementwise.cc \
../tflm/tensorflow/lite/micro/kernels/elu.cc \
../tflm/tensorflow/lite/micro/kernels/embedding_lookup.cc \
../tflm/tensorflow/lite/micro/kernels/ethosu.cc \
../tflm/tensorflow/lite/micro/kernels/exp.cc \
../tflm/tensorflow/lite/micro/kernels/expand_dims.cc \
../tflm/tensorflow/lite/micro/kernels/fill.cc \
../tflm/tensorflow/lite/micro/kernels/floor.cc \
../tflm/tensorflow/lite/micro/kernels/floor_div.cc \
../tflm/tensorflow/lite/micro/kernels/floor_mod.cc \
../tflm/tensorflow/lite/micro/kernels/fully_connected_common.cc \
../tflm/tensorflow/lite/micro/kernels/gather.cc \
../tflm/tensorflow/lite/micro/kernels/gather_nd.cc \
../tflm/tensorflow/lite/micro/kernels/hard_swish.cc \
../tflm/tensorflow/lite/micro/kernels/hard_swish_common.cc \
../tflm/tensorflow/lite/micro/kernels/if.cc \
../tflm/tensorflow/lite/micro/kernels/kernel_runner.cc \
../tflm/tensorflow/lite/micro/kernels/kernel_util.cc \
../tflm/tensorflow/lite/micro/kernels/l2_pool_2d.cc \
../tflm/tensorflow/lite/micro/kernels/l2norm.cc \
../tflm/tensorflow/lite/micro/kernels/leaky_relu.cc \
../tflm/tensorflow/lite/micro/kernels/leaky_relu_common.cc \
../tflm/tensorflow/lite/micro/kernels/log_softmax.cc \
../tflm/tensorflow/lite/micro/kernels/logical.cc \
../tflm/tensorflow/lite/micro/kernels/logical_common.cc \
../tflm/tensorflow/lite/micro/kernels/logistic.cc \
../tflm/tensorflow/lite/micro/kernels/logistic_common.cc \
../tflm/tensorflow/lite/micro/kernels/lstm_eval.cc \
../tflm/tensorflow/lite/micro/kernels/lstm_eval_common.cc \
../tflm/tensorflow/lite/micro/kernels/maximum_minimum.cc \
../tflm/tensorflow/lite/micro/kernels/micro_tensor_utils.cc \
../tflm/tensorflow/lite/micro/kernels/mirror_pad.cc \
../tflm/tensorflow/lite/micro/kernels/mul_common.cc \
../tflm/tensorflow/lite/micro/kernels/neg.cc \
../tflm/tensorflow/lite/micro/kernels/pack.cc \
../tflm/tensorflow/lite/micro/kernels/pad.cc \
../tflm/tensorflow/lite/micro/kernels/pooling_common.cc \
../tflm/tensorflow/lite/micro/kernels/prelu.cc \
../tflm/tensorflow/lite/micro/kernels/prelu_common.cc \
../tflm/tensorflow/lite/micro/kernels/quantize.cc \
../tflm/tensorflow/lite/micro/kernels/quantize_common.cc \
../tflm/tensorflow/lite/micro/kernels/read_variable.cc \
../tflm/tensorflow/lite/micro/kernels/reduce.cc \
../tflm/tensorflow/lite/micro/kernels/reduce_common.cc \
../tflm/tensorflow/lite/micro/kernels/reshape.cc \
../tflm/tensorflow/lite/micro/kernels/reshape_common.cc \
../tflm/tensorflow/lite/micro/kernels/resize_bilinear.cc \
../tflm/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cc \
../tflm/tensorflow/lite/micro/kernels/round.cc \
../tflm/tensorflow/lite/micro/kernels/select.cc \
../tflm/tensorflow/lite/micro/kernels/shape.cc \
../tflm/tensorflow/lite/micro/kernels/slice.cc \
../tflm/tensorflow/lite/micro/kernels/softmax_common.cc \
../tflm/tensorflow/lite/micro/kernels/space_to_batch_nd.cc \
../tflm/tensorflow/lite/micro/kernels/space_to_depth.cc \
../tflm/tensorflow/lite/micro/kernels/split.cc \
../tflm/tensorflow/lite/micro/kernels/split_v.cc \
../tflm/tensorflow/lite/micro/kernels/squared_difference.cc \
../tflm/tensorflow/lite/micro/kernels/squeeze.cc \
../tflm/tensorflow/lite/micro/kernels/strided_slice.cc \
../tflm/tensorflow/lite/micro/kernels/strided_slice_common.cc \
../tflm/tensorflow/lite/micro/kernels/sub.cc \
../tflm/tensorflow/lite/micro/kernels/sub_common.cc \
../tflm/tensorflow/lite/micro/kernels/svdf_common.cc \
../tflm/tensorflow/lite/micro/kernels/tanh.cc \
../tflm/tensorflow/lite/micro/kernels/transpose.cc \
../tflm/tensorflow/lite/micro/kernels/unpack.cc \
../tflm/tensorflow/lite/micro/kernels/var_handle.cc \
../tflm/tensorflow/lite/micro/kernels/while.cc \
../tflm/tensorflow/lite/micro/kernels/zeros_like.cc 

CC_DEPS += \
./tflm/tensorflow/lite/micro/kernels/activations.d \
./tflm/tensorflow/lite/micro/kernels/activations_common.d \
./tflm/tensorflow/lite/micro/kernels/add_common.d \
./tflm/tensorflow/lite/micro/kernels/add_n.d \
./tflm/tensorflow/lite/micro/kernels/arg_min_max.d \
./tflm/tensorflow/lite/micro/kernels/assign_variable.d \
./tflm/tensorflow/lite/micro/kernels/batch_to_space_nd.d \
./tflm/tensorflow/lite/micro/kernels/broadcast_args.d \
./tflm/tensorflow/lite/micro/kernels/broadcast_to.d \
./tflm/tensorflow/lite/micro/kernels/call_once.d \
./tflm/tensorflow/lite/micro/kernels/cast.d \
./tflm/tensorflow/lite/micro/kernels/ceil.d \
./tflm/tensorflow/lite/micro/kernels/circular_buffer.d \
./tflm/tensorflow/lite/micro/kernels/circular_buffer_common.d \
./tflm/tensorflow/lite/micro/kernels/comparisons.d \
./tflm/tensorflow/lite/micro/kernels/concatenation.d \
./tflm/tensorflow/lite/micro/kernels/conv_common.d \
./tflm/tensorflow/lite/micro/kernels/cumsum.d \
./tflm/tensorflow/lite/micro/kernels/decompress.d \
./tflm/tensorflow/lite/micro/kernels/decompress_common.d \
./tflm/tensorflow/lite/micro/kernels/depth_to_space.d \
./tflm/tensorflow/lite/micro/kernels/depthwise_conv_common.d \
./tflm/tensorflow/lite/micro/kernels/dequantize.d \
./tflm/tensorflow/lite/micro/kernels/dequantize_common.d \
./tflm/tensorflow/lite/micro/kernels/detection_postprocess.d \
./tflm/tensorflow/lite/micro/kernels/div.d \
./tflm/tensorflow/lite/micro/kernels/elementwise.d \
./tflm/tensorflow/lite/micro/kernels/elu.d \
./tflm/tensorflow/lite/micro/kernels/embedding_lookup.d \
./tflm/tensorflow/lite/micro/kernels/ethosu.d \
./tflm/tensorflow/lite/micro/kernels/exp.d \
./tflm/tensorflow/lite/micro/kernels/expand_dims.d \
./tflm/tensorflow/lite/micro/kernels/fill.d \
./tflm/tensorflow/lite/micro/kernels/floor.d \
./tflm/tensorflow/lite/micro/kernels/floor_div.d \
./tflm/tensorflow/lite/micro/kernels/floor_mod.d \
./tflm/tensorflow/lite/micro/kernels/fully_connected_common.d \
./tflm/tensorflow/lite/micro/kernels/gather.d \
./tflm/tensorflow/lite/micro/kernels/gather_nd.d \
./tflm/tensorflow/lite/micro/kernels/hard_swish.d \
./tflm/tensorflow/lite/micro/kernels/hard_swish_common.d \
./tflm/tensorflow/lite/micro/kernels/if.d \
./tflm/tensorflow/lite/micro/kernels/kernel_runner.d \
./tflm/tensorflow/lite/micro/kernels/kernel_util.d \
./tflm/tensorflow/lite/micro/kernels/l2_pool_2d.d \
./tflm/tensorflow/lite/micro/kernels/l2norm.d \
./tflm/tensorflow/lite/micro/kernels/leaky_relu.d \
./tflm/tensorflow/lite/micro/kernels/leaky_relu_common.d \
./tflm/tensorflow/lite/micro/kernels/log_softmax.d \
./tflm/tensorflow/lite/micro/kernels/logical.d \
./tflm/tensorflow/lite/micro/kernels/logical_common.d \
./tflm/tensorflow/lite/micro/kernels/logistic.d \
./tflm/tensorflow/lite/micro/kernels/logistic_common.d \
./tflm/tensorflow/lite/micro/kernels/lstm_eval.d \
./tflm/tensorflow/lite/micro/kernels/lstm_eval_common.d \
./tflm/tensorflow/lite/micro/kernels/maximum_minimum.d \
./tflm/tensorflow/lite/micro/kernels/micro_tensor_utils.d \
./tflm/tensorflow/lite/micro/kernels/mirror_pad.d \
./tflm/tensorflow/lite/micro/kernels/mul_common.d \
./tflm/tensorflow/lite/micro/kernels/neg.d \
./tflm/tensorflow/lite/micro/kernels/pack.d \
./tflm/tensorflow/lite/micro/kernels/pad.d \
./tflm/tensorflow/lite/micro/kernels/pooling_common.d \
./tflm/tensorflow/lite/micro/kernels/prelu.d \
./tflm/tensorflow/lite/micro/kernels/prelu_common.d \
./tflm/tensorflow/lite/micro/kernels/quantize.d \
./tflm/tensorflow/lite/micro/kernels/quantize_common.d \
./tflm/tensorflow/lite/micro/kernels/read_variable.d \
./tflm/tensorflow/lite/micro/kernels/reduce.d \
./tflm/tensorflow/lite/micro/kernels/reduce_common.d \
./tflm/tensorflow/lite/micro/kernels/reshape.d \
./tflm/tensorflow/lite/micro/kernels/reshape_common.d \
./tflm/tensorflow/lite/micro/kernels/resize_bilinear.d \
./tflm/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d \
./tflm/tensorflow/lite/micro/kernels/round.d \
./tflm/tensorflow/lite/micro/kernels/select.d \
./tflm/tensorflow/lite/micro/kernels/shape.d \
./tflm/tensorflow/lite/micro/kernels/slice.d \
./tflm/tensorflow/lite/micro/kernels/softmax_common.d \
./tflm/tensorflow/lite/micro/kernels/space_to_batch_nd.d \
./tflm/tensorflow/lite/micro/kernels/space_to_depth.d \
./tflm/tensorflow/lite/micro/kernels/split.d \
./tflm/tensorflow/lite/micro/kernels/split_v.d \
./tflm/tensorflow/lite/micro/kernels/squared_difference.d \
./tflm/tensorflow/lite/micro/kernels/squeeze.d \
./tflm/tensorflow/lite/micro/kernels/strided_slice.d \
./tflm/tensorflow/lite/micro/kernels/strided_slice_common.d \
./tflm/tensorflow/lite/micro/kernels/sub.d \
./tflm/tensorflow/lite/micro/kernels/sub_common.d \
./tflm/tensorflow/lite/micro/kernels/svdf_common.d \
./tflm/tensorflow/lite/micro/kernels/tanh.d \
./tflm/tensorflow/lite/micro/kernels/transpose.d \
./tflm/tensorflow/lite/micro/kernels/unpack.d \
./tflm/tensorflow/lite/micro/kernels/var_handle.d \
./tflm/tensorflow/lite/micro/kernels/while.d \
./tflm/tensorflow/lite/micro/kernels/zeros_like.d 

OBJS += \
./tflm/tensorflow/lite/micro/kernels/activations.o \
./tflm/tensorflow/lite/micro/kernels/activations_common.o \
./tflm/tensorflow/lite/micro/kernels/add_common.o \
./tflm/tensorflow/lite/micro/kernels/add_n.o \
./tflm/tensorflow/lite/micro/kernels/arg_min_max.o \
./tflm/tensorflow/lite/micro/kernels/assign_variable.o \
./tflm/tensorflow/lite/micro/kernels/batch_to_space_nd.o \
./tflm/tensorflow/lite/micro/kernels/broadcast_args.o \
./tflm/tensorflow/lite/micro/kernels/broadcast_to.o \
./tflm/tensorflow/lite/micro/kernels/call_once.o \
./tflm/tensorflow/lite/micro/kernels/cast.o \
./tflm/tensorflow/lite/micro/kernels/ceil.o \
./tflm/tensorflow/lite/micro/kernels/circular_buffer.o \
./tflm/tensorflow/lite/micro/kernels/circular_buffer_common.o \
./tflm/tensorflow/lite/micro/kernels/comparisons.o \
./tflm/tensorflow/lite/micro/kernels/concatenation.o \
./tflm/tensorflow/lite/micro/kernels/conv_common.o \
./tflm/tensorflow/lite/micro/kernels/cumsum.o \
./tflm/tensorflow/lite/micro/kernels/decompress.o \
./tflm/tensorflow/lite/micro/kernels/decompress_common.o \
./tflm/tensorflow/lite/micro/kernels/depth_to_space.o \
./tflm/tensorflow/lite/micro/kernels/depthwise_conv_common.o \
./tflm/tensorflow/lite/micro/kernels/dequantize.o \
./tflm/tensorflow/lite/micro/kernels/dequantize_common.o \
./tflm/tensorflow/lite/micro/kernels/detection_postprocess.o \
./tflm/tensorflow/lite/micro/kernels/div.o \
./tflm/tensorflow/lite/micro/kernels/elementwise.o \
./tflm/tensorflow/lite/micro/kernels/elu.o \
./tflm/tensorflow/lite/micro/kernels/embedding_lookup.o \
./tflm/tensorflow/lite/micro/kernels/ethosu.o \
./tflm/tensorflow/lite/micro/kernels/exp.o \
./tflm/tensorflow/lite/micro/kernels/expand_dims.o \
./tflm/tensorflow/lite/micro/kernels/fill.o \
./tflm/tensorflow/lite/micro/kernels/floor.o \
./tflm/tensorflow/lite/micro/kernels/floor_div.o \
./tflm/tensorflow/lite/micro/kernels/floor_mod.o \
./tflm/tensorflow/lite/micro/kernels/fully_connected_common.o \
./tflm/tensorflow/lite/micro/kernels/gather.o \
./tflm/tensorflow/lite/micro/kernels/gather_nd.o \
./tflm/tensorflow/lite/micro/kernels/hard_swish.o \
./tflm/tensorflow/lite/micro/kernels/hard_swish_common.o \
./tflm/tensorflow/lite/micro/kernels/if.o \
./tflm/tensorflow/lite/micro/kernels/kernel_runner.o \
./tflm/tensorflow/lite/micro/kernels/kernel_util.o \
./tflm/tensorflow/lite/micro/kernels/l2_pool_2d.o \
./tflm/tensorflow/lite/micro/kernels/l2norm.o \
./tflm/tensorflow/lite/micro/kernels/leaky_relu.o \
./tflm/tensorflow/lite/micro/kernels/leaky_relu_common.o \
./tflm/tensorflow/lite/micro/kernels/log_softmax.o \
./tflm/tensorflow/lite/micro/kernels/logical.o \
./tflm/tensorflow/lite/micro/kernels/logical_common.o \
./tflm/tensorflow/lite/micro/kernels/logistic.o \
./tflm/tensorflow/lite/micro/kernels/logistic_common.o \
./tflm/tensorflow/lite/micro/kernels/lstm_eval.o \
./tflm/tensorflow/lite/micro/kernels/lstm_eval_common.o \
./tflm/tensorflow/lite/micro/kernels/maximum_minimum.o \
./tflm/tensorflow/lite/micro/kernels/micro_tensor_utils.o \
./tflm/tensorflow/lite/micro/kernels/mirror_pad.o \
./tflm/tensorflow/lite/micro/kernels/mul_common.o \
./tflm/tensorflow/lite/micro/kernels/neg.o \
./tflm/tensorflow/lite/micro/kernels/pack.o \
./tflm/tensorflow/lite/micro/kernels/pad.o \
./tflm/tensorflow/lite/micro/kernels/pooling_common.o \
./tflm/tensorflow/lite/micro/kernels/prelu.o \
./tflm/tensorflow/lite/micro/kernels/prelu_common.o \
./tflm/tensorflow/lite/micro/kernels/quantize.o \
./tflm/tensorflow/lite/micro/kernels/quantize_common.o \
./tflm/tensorflow/lite/micro/kernels/read_variable.o \
./tflm/tensorflow/lite/micro/kernels/reduce.o \
./tflm/tensorflow/lite/micro/kernels/reduce_common.o \
./tflm/tensorflow/lite/micro/kernels/reshape.o \
./tflm/tensorflow/lite/micro/kernels/reshape_common.o \
./tflm/tensorflow/lite/micro/kernels/resize_bilinear.o \
./tflm/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o \
./tflm/tensorflow/lite/micro/kernels/round.o \
./tflm/tensorflow/lite/micro/kernels/select.o \
./tflm/tensorflow/lite/micro/kernels/shape.o \
./tflm/tensorflow/lite/micro/kernels/slice.o \
./tflm/tensorflow/lite/micro/kernels/softmax_common.o \
./tflm/tensorflow/lite/micro/kernels/space_to_batch_nd.o \
./tflm/tensorflow/lite/micro/kernels/space_to_depth.o \
./tflm/tensorflow/lite/micro/kernels/split.o \
./tflm/tensorflow/lite/micro/kernels/split_v.o \
./tflm/tensorflow/lite/micro/kernels/squared_difference.o \
./tflm/tensorflow/lite/micro/kernels/squeeze.o \
./tflm/tensorflow/lite/micro/kernels/strided_slice.o \
./tflm/tensorflow/lite/micro/kernels/strided_slice_common.o \
./tflm/tensorflow/lite/micro/kernels/sub.o \
./tflm/tensorflow/lite/micro/kernels/sub_common.o \
./tflm/tensorflow/lite/micro/kernels/svdf_common.o \
./tflm/tensorflow/lite/micro/kernels/tanh.o \
./tflm/tensorflow/lite/micro/kernels/transpose.o \
./tflm/tensorflow/lite/micro/kernels/unpack.o \
./tflm/tensorflow/lite/micro/kernels/var_handle.o \
./tflm/tensorflow/lite/micro/kernels/while.o \
./tflm/tensorflow/lite/micro/kernels/zeros_like.o 


# Each subdirectory must supply rules for building sources it contributes
tflm/tensorflow/lite/micro/kernels/%.o tflm/tensorflow/lite/micro/kernels/%.su tflm/tensorflow/lite/micro/kernels/%.cyclo: ../tflm/tensorflow/lite/micro/kernels/%.cc tflm/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Bazar/Desktop/My-STM32_Discoveries/STM32F411_Discovery/STM32F411Discovery_SineWave_TFLite/SineWave_TFLite/tensorflow_lite" -I"C:/Users/Bazar/Desktop/My-STM32_Discoveries/STM32F411_Discovery/STM32F411Discovery_SineWave_TFLite/SineWave_TFLite/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/Bazar/Desktop/My-STM32_Discoveries/STM32F411_Discovery/STM32F411Discovery_SineWave_TFLite/SineWave_TFLite/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/Bazar/Desktop/My-STM32_Discoveries/STM32F411_Discovery/STM32F411Discovery_SineWave_TFLite/SineWave_TFLite/tensorflow_lite/third_party/ruy" -I"C:/Users/Bazar/Desktop/My-STM32_Discoveries/STM32F411_Discovery/STM32F411Discovery_SineWave_TFLite/SineWave_TFLite/tensorflow_lite/third_party/kissfft" -I"C:/Users/Bazar/Desktop/My-STM32_Discoveries/STM32F411_Discovery/STM32F411Discovery_SineWave_TFLite/SineWave_TFLite/tensorflow_lite/tensorflow/lite" -I"C:/Users/Bazar/Desktop/My-STM32_Discoveries/STM32F411_Discovery/STM32F411Discovery_SineWave_TFLite/SineWave_TFLite/tflm" -I"C:/Users/Bazar/Desktop/My-STM32_Discoveries/STM32F411_Discovery/STM32F411Discovery_SineWave_TFLite/SineWave_TFLite/tflm/tensorflow/lite" -I"C:/Users/Bazar/Desktop/My-STM32_Discoveries/STM32F411_Discovery/STM32F411Discovery_SineWave_TFLite/SineWave_TFLite/tflm/third_party/flatbuffers/include" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-tflm-2f-tensorflow-2f-lite-2f-micro-2f-kernels

clean-tflm-2f-tensorflow-2f-lite-2f-micro-2f-kernels:
	-$(RM) ./tflm/tensorflow/lite/micro/kernels/activations.cyclo ./tflm/tensorflow/lite/micro/kernels/activations.d ./tflm/tensorflow/lite/micro/kernels/activations.o ./tflm/tensorflow/lite/micro/kernels/activations.su ./tflm/tensorflow/lite/micro/kernels/activations_common.cyclo ./tflm/tensorflow/lite/micro/kernels/activations_common.d ./tflm/tensorflow/lite/micro/kernels/activations_common.o ./tflm/tensorflow/lite/micro/kernels/activations_common.su ./tflm/tensorflow/lite/micro/kernels/add_common.cyclo ./tflm/tensorflow/lite/micro/kernels/add_common.d ./tflm/tensorflow/lite/micro/kernels/add_common.o ./tflm/tensorflow/lite/micro/kernels/add_common.su ./tflm/tensorflow/lite/micro/kernels/add_n.cyclo ./tflm/tensorflow/lite/micro/kernels/add_n.d ./tflm/tensorflow/lite/micro/kernels/add_n.o ./tflm/tensorflow/lite/micro/kernels/add_n.su ./tflm/tensorflow/lite/micro/kernels/arg_min_max.cyclo ./tflm/tensorflow/lite/micro/kernels/arg_min_max.d ./tflm/tensorflow/lite/micro/kernels/arg_min_max.o ./tflm/tensorflow/lite/micro/kernels/arg_min_max.su ./tflm/tensorflow/lite/micro/kernels/assign_variable.cyclo ./tflm/tensorflow/lite/micro/kernels/assign_variable.d ./tflm/tensorflow/lite/micro/kernels/assign_variable.o ./tflm/tensorflow/lite/micro/kernels/assign_variable.su ./tflm/tensorflow/lite/micro/kernels/batch_to_space_nd.cyclo ./tflm/tensorflow/lite/micro/kernels/batch_to_space_nd.d ./tflm/tensorflow/lite/micro/kernels/batch_to_space_nd.o ./tflm/tensorflow/lite/micro/kernels/batch_to_space_nd.su ./tflm/tensorflow/lite/micro/kernels/broadcast_args.cyclo ./tflm/tensorflow/lite/micro/kernels/broadcast_args.d ./tflm/tensorflow/lite/micro/kernels/broadcast_args.o ./tflm/tensorflow/lite/micro/kernels/broadcast_args.su ./tflm/tensorflow/lite/micro/kernels/broadcast_to.cyclo ./tflm/tensorflow/lite/micro/kernels/broadcast_to.d ./tflm/tensorflow/lite/micro/kernels/broadcast_to.o ./tflm/tensorflow/lite/micro/kernels/broadcast_to.su ./tflm/tensorflow/lite/micro/kernels/call_once.cyclo ./tflm/tensorflow/lite/micro/kernels/call_once.d ./tflm/tensorflow/lite/micro/kernels/call_once.o ./tflm/tensorflow/lite/micro/kernels/call_once.su ./tflm/tensorflow/lite/micro/kernels/cast.cyclo ./tflm/tensorflow/lite/micro/kernels/cast.d ./tflm/tensorflow/lite/micro/kernels/cast.o ./tflm/tensorflow/lite/micro/kernels/cast.su ./tflm/tensorflow/lite/micro/kernels/ceil.cyclo ./tflm/tensorflow/lite/micro/kernels/ceil.d ./tflm/tensorflow/lite/micro/kernels/ceil.o ./tflm/tensorflow/lite/micro/kernels/ceil.su ./tflm/tensorflow/lite/micro/kernels/circular_buffer.cyclo ./tflm/tensorflow/lite/micro/kernels/circular_buffer.d ./tflm/tensorflow/lite/micro/kernels/circular_buffer.o ./tflm/tensorflow/lite/micro/kernels/circular_buffer.su ./tflm/tensorflow/lite/micro/kernels/circular_buffer_common.cyclo ./tflm/tensorflow/lite/micro/kernels/circular_buffer_common.d ./tflm/tensorflow/lite/micro/kernels/circular_buffer_common.o ./tflm/tensorflow/lite/micro/kernels/circular_buffer_common.su ./tflm/tensorflow/lite/micro/kernels/comparisons.cyclo ./tflm/tensorflow/lite/micro/kernels/comparisons.d ./tflm/tensorflow/lite/micro/kernels/comparisons.o ./tflm/tensorflow/lite/micro/kernels/comparisons.su ./tflm/tensorflow/lite/micro/kernels/concatenation.cyclo ./tflm/tensorflow/lite/micro/kernels/concatenation.d ./tflm/tensorflow/lite/micro/kernels/concatenation.o ./tflm/tensorflow/lite/micro/kernels/concatenation.su ./tflm/tensorflow/lite/micro/kernels/conv_common.cyclo ./tflm/tensorflow/lite/micro/kernels/conv_common.d ./tflm/tensorflow/lite/micro/kernels/conv_common.o ./tflm/tensorflow/lite/micro/kernels/conv_common.su ./tflm/tensorflow/lite/micro/kernels/cumsum.cyclo ./tflm/tensorflow/lite/micro/kernels/cumsum.d ./tflm/tensorflow/lite/micro/kernels/cumsum.o ./tflm/tensorflow/lite/micro/kernels/cumsum.su ./tflm/tensorflow/lite/micro/kernels/decompress.cyclo ./tflm/tensorflow/lite/micro/kernels/decompress.d ./tflm/tensorflow/lite/micro/kernels/decompress.o ./tflm/tensorflow/lite/micro/kernels/decompress.su ./tflm/tensorflow/lite/micro/kernels/decompress_common.cyclo ./tflm/tensorflow/lite/micro/kernels/decompress_common.d ./tflm/tensorflow/lite/micro/kernels/decompress_common.o ./tflm/tensorflow/lite/micro/kernels/decompress_common.su ./tflm/tensorflow/lite/micro/kernels/depth_to_space.cyclo ./tflm/tensorflow/lite/micro/kernels/depth_to_space.d ./tflm/tensorflow/lite/micro/kernels/depth_to_space.o ./tflm/tensorflow/lite/micro/kernels/depth_to_space.su ./tflm/tensorflow/lite/micro/kernels/depthwise_conv_common.cyclo ./tflm/tensorflow/lite/micro/kernels/depthwise_conv_common.d ./tflm/tensorflow/lite/micro/kernels/depthwise_conv_common.o ./tflm/tensorflow/lite/micro/kernels/depthwise_conv_common.su ./tflm/tensorflow/lite/micro/kernels/dequantize.cyclo ./tflm/tensorflow/lite/micro/kernels/dequantize.d ./tflm/tensorflow/lite/micro/kernels/dequantize.o ./tflm/tensorflow/lite/micro/kernels/dequantize.su ./tflm/tensorflow/lite/micro/kernels/dequantize_common.cyclo ./tflm/tensorflow/lite/micro/kernels/dequantize_common.d ./tflm/tensorflow/lite/micro/kernels/dequantize_common.o ./tflm/tensorflow/lite/micro/kernels/dequantize_common.su ./tflm/tensorflow/lite/micro/kernels/detection_postprocess.cyclo ./tflm/tensorflow/lite/micro/kernels/detection_postprocess.d ./tflm/tensorflow/lite/micro/kernels/detection_postprocess.o ./tflm/tensorflow/lite/micro/kernels/detection_postprocess.su ./tflm/tensorflow/lite/micro/kernels/div.cyclo ./tflm/tensorflow/lite/micro/kernels/div.d ./tflm/tensorflow/lite/micro/kernels/div.o ./tflm/tensorflow/lite/micro/kernels/div.su ./tflm/tensorflow/lite/micro/kernels/elementwise.cyclo ./tflm/tensorflow/lite/micro/kernels/elementwise.d ./tflm/tensorflow/lite/micro/kernels/elementwise.o ./tflm/tensorflow/lite/micro/kernels/elementwise.su ./tflm/tensorflow/lite/micro/kernels/elu.cyclo ./tflm/tensorflow/lite/micro/kernels/elu.d ./tflm/tensorflow/lite/micro/kernels/elu.o ./tflm/tensorflow/lite/micro/kernels/elu.su
	-$(RM) ./tflm/tensorflow/lite/micro/kernels/embedding_lookup.cyclo ./tflm/tensorflow/lite/micro/kernels/embedding_lookup.d ./tflm/tensorflow/lite/micro/kernels/embedding_lookup.o ./tflm/tensorflow/lite/micro/kernels/embedding_lookup.su ./tflm/tensorflow/lite/micro/kernels/ethosu.cyclo ./tflm/tensorflow/lite/micro/kernels/ethosu.d ./tflm/tensorflow/lite/micro/kernels/ethosu.o ./tflm/tensorflow/lite/micro/kernels/ethosu.su ./tflm/tensorflow/lite/micro/kernels/exp.cyclo ./tflm/tensorflow/lite/micro/kernels/exp.d ./tflm/tensorflow/lite/micro/kernels/exp.o ./tflm/tensorflow/lite/micro/kernels/exp.su ./tflm/tensorflow/lite/micro/kernels/expand_dims.cyclo ./tflm/tensorflow/lite/micro/kernels/expand_dims.d ./tflm/tensorflow/lite/micro/kernels/expand_dims.o ./tflm/tensorflow/lite/micro/kernels/expand_dims.su ./tflm/tensorflow/lite/micro/kernels/fill.cyclo ./tflm/tensorflow/lite/micro/kernels/fill.d ./tflm/tensorflow/lite/micro/kernels/fill.o ./tflm/tensorflow/lite/micro/kernels/fill.su ./tflm/tensorflow/lite/micro/kernels/floor.cyclo ./tflm/tensorflow/lite/micro/kernels/floor.d ./tflm/tensorflow/lite/micro/kernels/floor.o ./tflm/tensorflow/lite/micro/kernels/floor.su ./tflm/tensorflow/lite/micro/kernels/floor_div.cyclo ./tflm/tensorflow/lite/micro/kernels/floor_div.d ./tflm/tensorflow/lite/micro/kernels/floor_div.o ./tflm/tensorflow/lite/micro/kernels/floor_div.su ./tflm/tensorflow/lite/micro/kernels/floor_mod.cyclo ./tflm/tensorflow/lite/micro/kernels/floor_mod.d ./tflm/tensorflow/lite/micro/kernels/floor_mod.o ./tflm/tensorflow/lite/micro/kernels/floor_mod.su ./tflm/tensorflow/lite/micro/kernels/fully_connected_common.cyclo ./tflm/tensorflow/lite/micro/kernels/fully_connected_common.d ./tflm/tensorflow/lite/micro/kernels/fully_connected_common.o ./tflm/tensorflow/lite/micro/kernels/fully_connected_common.su ./tflm/tensorflow/lite/micro/kernels/gather.cyclo ./tflm/tensorflow/lite/micro/kernels/gather.d ./tflm/tensorflow/lite/micro/kernels/gather.o ./tflm/tensorflow/lite/micro/kernels/gather.su ./tflm/tensorflow/lite/micro/kernels/gather_nd.cyclo ./tflm/tensorflow/lite/micro/kernels/gather_nd.d ./tflm/tensorflow/lite/micro/kernels/gather_nd.o ./tflm/tensorflow/lite/micro/kernels/gather_nd.su ./tflm/tensorflow/lite/micro/kernels/hard_swish.cyclo ./tflm/tensorflow/lite/micro/kernels/hard_swish.d ./tflm/tensorflow/lite/micro/kernels/hard_swish.o ./tflm/tensorflow/lite/micro/kernels/hard_swish.su ./tflm/tensorflow/lite/micro/kernels/hard_swish_common.cyclo ./tflm/tensorflow/lite/micro/kernels/hard_swish_common.d ./tflm/tensorflow/lite/micro/kernels/hard_swish_common.o ./tflm/tensorflow/lite/micro/kernels/hard_swish_common.su ./tflm/tensorflow/lite/micro/kernels/if.cyclo ./tflm/tensorflow/lite/micro/kernels/if.d ./tflm/tensorflow/lite/micro/kernels/if.o ./tflm/tensorflow/lite/micro/kernels/if.su ./tflm/tensorflow/lite/micro/kernels/kernel_runner.cyclo ./tflm/tensorflow/lite/micro/kernels/kernel_runner.d ./tflm/tensorflow/lite/micro/kernels/kernel_runner.o ./tflm/tensorflow/lite/micro/kernels/kernel_runner.su ./tflm/tensorflow/lite/micro/kernels/kernel_util.cyclo ./tflm/tensorflow/lite/micro/kernels/kernel_util.d ./tflm/tensorflow/lite/micro/kernels/kernel_util.o ./tflm/tensorflow/lite/micro/kernels/kernel_util.su ./tflm/tensorflow/lite/micro/kernels/l2_pool_2d.cyclo ./tflm/tensorflow/lite/micro/kernels/l2_pool_2d.d ./tflm/tensorflow/lite/micro/kernels/l2_pool_2d.o ./tflm/tensorflow/lite/micro/kernels/l2_pool_2d.su ./tflm/tensorflow/lite/micro/kernels/l2norm.cyclo ./tflm/tensorflow/lite/micro/kernels/l2norm.d ./tflm/tensorflow/lite/micro/kernels/l2norm.o ./tflm/tensorflow/lite/micro/kernels/l2norm.su ./tflm/tensorflow/lite/micro/kernels/leaky_relu.cyclo ./tflm/tensorflow/lite/micro/kernels/leaky_relu.d ./tflm/tensorflow/lite/micro/kernels/leaky_relu.o ./tflm/tensorflow/lite/micro/kernels/leaky_relu.su ./tflm/tensorflow/lite/micro/kernels/leaky_relu_common.cyclo ./tflm/tensorflow/lite/micro/kernels/leaky_relu_common.d ./tflm/tensorflow/lite/micro/kernels/leaky_relu_common.o ./tflm/tensorflow/lite/micro/kernels/leaky_relu_common.su ./tflm/tensorflow/lite/micro/kernels/log_softmax.cyclo ./tflm/tensorflow/lite/micro/kernels/log_softmax.d ./tflm/tensorflow/lite/micro/kernels/log_softmax.o ./tflm/tensorflow/lite/micro/kernels/log_softmax.su ./tflm/tensorflow/lite/micro/kernels/logical.cyclo ./tflm/tensorflow/lite/micro/kernels/logical.d ./tflm/tensorflow/lite/micro/kernels/logical.o ./tflm/tensorflow/lite/micro/kernels/logical.su ./tflm/tensorflow/lite/micro/kernels/logical_common.cyclo ./tflm/tensorflow/lite/micro/kernels/logical_common.d ./tflm/tensorflow/lite/micro/kernels/logical_common.o ./tflm/tensorflow/lite/micro/kernels/logical_common.su ./tflm/tensorflow/lite/micro/kernels/logistic.cyclo ./tflm/tensorflow/lite/micro/kernels/logistic.d ./tflm/tensorflow/lite/micro/kernels/logistic.o ./tflm/tensorflow/lite/micro/kernels/logistic.su ./tflm/tensorflow/lite/micro/kernels/logistic_common.cyclo ./tflm/tensorflow/lite/micro/kernels/logistic_common.d ./tflm/tensorflow/lite/micro/kernels/logistic_common.o ./tflm/tensorflow/lite/micro/kernels/logistic_common.su ./tflm/tensorflow/lite/micro/kernels/lstm_eval.cyclo ./tflm/tensorflow/lite/micro/kernels/lstm_eval.d ./tflm/tensorflow/lite/micro/kernels/lstm_eval.o ./tflm/tensorflow/lite/micro/kernels/lstm_eval.su ./tflm/tensorflow/lite/micro/kernels/lstm_eval_common.cyclo ./tflm/tensorflow/lite/micro/kernels/lstm_eval_common.d ./tflm/tensorflow/lite/micro/kernels/lstm_eval_common.o ./tflm/tensorflow/lite/micro/kernels/lstm_eval_common.su ./tflm/tensorflow/lite/micro/kernels/maximum_minimum.cyclo ./tflm/tensorflow/lite/micro/kernels/maximum_minimum.d ./tflm/tensorflow/lite/micro/kernels/maximum_minimum.o ./tflm/tensorflow/lite/micro/kernels/maximum_minimum.su ./tflm/tensorflow/lite/micro/kernels/micro_tensor_utils.cyclo ./tflm/tensorflow/lite/micro/kernels/micro_tensor_utils.d ./tflm/tensorflow/lite/micro/kernels/micro_tensor_utils.o
	-$(RM) ./tflm/tensorflow/lite/micro/kernels/micro_tensor_utils.su ./tflm/tensorflow/lite/micro/kernels/mirror_pad.cyclo ./tflm/tensorflow/lite/micro/kernels/mirror_pad.d ./tflm/tensorflow/lite/micro/kernels/mirror_pad.o ./tflm/tensorflow/lite/micro/kernels/mirror_pad.su ./tflm/tensorflow/lite/micro/kernels/mul_common.cyclo ./tflm/tensorflow/lite/micro/kernels/mul_common.d ./tflm/tensorflow/lite/micro/kernels/mul_common.o ./tflm/tensorflow/lite/micro/kernels/mul_common.su ./tflm/tensorflow/lite/micro/kernels/neg.cyclo ./tflm/tensorflow/lite/micro/kernels/neg.d ./tflm/tensorflow/lite/micro/kernels/neg.o ./tflm/tensorflow/lite/micro/kernels/neg.su ./tflm/tensorflow/lite/micro/kernels/pack.cyclo ./tflm/tensorflow/lite/micro/kernels/pack.d ./tflm/tensorflow/lite/micro/kernels/pack.o ./tflm/tensorflow/lite/micro/kernels/pack.su ./tflm/tensorflow/lite/micro/kernels/pad.cyclo ./tflm/tensorflow/lite/micro/kernels/pad.d ./tflm/tensorflow/lite/micro/kernels/pad.o ./tflm/tensorflow/lite/micro/kernels/pad.su ./tflm/tensorflow/lite/micro/kernels/pooling_common.cyclo ./tflm/tensorflow/lite/micro/kernels/pooling_common.d ./tflm/tensorflow/lite/micro/kernels/pooling_common.o ./tflm/tensorflow/lite/micro/kernels/pooling_common.su ./tflm/tensorflow/lite/micro/kernels/prelu.cyclo ./tflm/tensorflow/lite/micro/kernels/prelu.d ./tflm/tensorflow/lite/micro/kernels/prelu.o ./tflm/tensorflow/lite/micro/kernels/prelu.su ./tflm/tensorflow/lite/micro/kernels/prelu_common.cyclo ./tflm/tensorflow/lite/micro/kernels/prelu_common.d ./tflm/tensorflow/lite/micro/kernels/prelu_common.o ./tflm/tensorflow/lite/micro/kernels/prelu_common.su ./tflm/tensorflow/lite/micro/kernels/quantize.cyclo ./tflm/tensorflow/lite/micro/kernels/quantize.d ./tflm/tensorflow/lite/micro/kernels/quantize.o ./tflm/tensorflow/lite/micro/kernels/quantize.su ./tflm/tensorflow/lite/micro/kernels/quantize_common.cyclo ./tflm/tensorflow/lite/micro/kernels/quantize_common.d ./tflm/tensorflow/lite/micro/kernels/quantize_common.o ./tflm/tensorflow/lite/micro/kernels/quantize_common.su ./tflm/tensorflow/lite/micro/kernels/read_variable.cyclo ./tflm/tensorflow/lite/micro/kernels/read_variable.d ./tflm/tensorflow/lite/micro/kernels/read_variable.o ./tflm/tensorflow/lite/micro/kernels/read_variable.su ./tflm/tensorflow/lite/micro/kernels/reduce.cyclo ./tflm/tensorflow/lite/micro/kernels/reduce.d ./tflm/tensorflow/lite/micro/kernels/reduce.o ./tflm/tensorflow/lite/micro/kernels/reduce.su ./tflm/tensorflow/lite/micro/kernels/reduce_common.cyclo ./tflm/tensorflow/lite/micro/kernels/reduce_common.d ./tflm/tensorflow/lite/micro/kernels/reduce_common.o ./tflm/tensorflow/lite/micro/kernels/reduce_common.su ./tflm/tensorflow/lite/micro/kernels/reshape.cyclo ./tflm/tensorflow/lite/micro/kernels/reshape.d ./tflm/tensorflow/lite/micro/kernels/reshape.o ./tflm/tensorflow/lite/micro/kernels/reshape.su ./tflm/tensorflow/lite/micro/kernels/reshape_common.cyclo ./tflm/tensorflow/lite/micro/kernels/reshape_common.d ./tflm/tensorflow/lite/micro/kernels/reshape_common.o ./tflm/tensorflow/lite/micro/kernels/reshape_common.su ./tflm/tensorflow/lite/micro/kernels/resize_bilinear.cyclo ./tflm/tensorflow/lite/micro/kernels/resize_bilinear.d ./tflm/tensorflow/lite/micro/kernels/resize_bilinear.o ./tflm/tensorflow/lite/micro/kernels/resize_bilinear.su ./tflm/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cyclo ./tflm/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d ./tflm/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o ./tflm/tensorflow/lite/micro/kernels/resize_nearest_neighbor.su ./tflm/tensorflow/lite/micro/kernels/round.cyclo ./tflm/tensorflow/lite/micro/kernels/round.d ./tflm/tensorflow/lite/micro/kernels/round.o ./tflm/tensorflow/lite/micro/kernels/round.su ./tflm/tensorflow/lite/micro/kernels/select.cyclo ./tflm/tensorflow/lite/micro/kernels/select.d ./tflm/tensorflow/lite/micro/kernels/select.o ./tflm/tensorflow/lite/micro/kernels/select.su ./tflm/tensorflow/lite/micro/kernels/shape.cyclo ./tflm/tensorflow/lite/micro/kernels/shape.d ./tflm/tensorflow/lite/micro/kernels/shape.o ./tflm/tensorflow/lite/micro/kernels/shape.su ./tflm/tensorflow/lite/micro/kernels/slice.cyclo ./tflm/tensorflow/lite/micro/kernels/slice.d ./tflm/tensorflow/lite/micro/kernels/slice.o ./tflm/tensorflow/lite/micro/kernels/slice.su ./tflm/tensorflow/lite/micro/kernels/softmax_common.cyclo ./tflm/tensorflow/lite/micro/kernels/softmax_common.d ./tflm/tensorflow/lite/micro/kernels/softmax_common.o ./tflm/tensorflow/lite/micro/kernels/softmax_common.su ./tflm/tensorflow/lite/micro/kernels/space_to_batch_nd.cyclo ./tflm/tensorflow/lite/micro/kernels/space_to_batch_nd.d ./tflm/tensorflow/lite/micro/kernels/space_to_batch_nd.o ./tflm/tensorflow/lite/micro/kernels/space_to_batch_nd.su ./tflm/tensorflow/lite/micro/kernels/space_to_depth.cyclo ./tflm/tensorflow/lite/micro/kernels/space_to_depth.d ./tflm/tensorflow/lite/micro/kernels/space_to_depth.o ./tflm/tensorflow/lite/micro/kernels/space_to_depth.su ./tflm/tensorflow/lite/micro/kernels/split.cyclo ./tflm/tensorflow/lite/micro/kernels/split.d ./tflm/tensorflow/lite/micro/kernels/split.o ./tflm/tensorflow/lite/micro/kernels/split.su ./tflm/tensorflow/lite/micro/kernels/split_v.cyclo ./tflm/tensorflow/lite/micro/kernels/split_v.d ./tflm/tensorflow/lite/micro/kernels/split_v.o ./tflm/tensorflow/lite/micro/kernels/split_v.su ./tflm/tensorflow/lite/micro/kernels/squared_difference.cyclo ./tflm/tensorflow/lite/micro/kernels/squared_difference.d ./tflm/tensorflow/lite/micro/kernels/squared_difference.o ./tflm/tensorflow/lite/micro/kernels/squared_difference.su ./tflm/tensorflow/lite/micro/kernels/squeeze.cyclo ./tflm/tensorflow/lite/micro/kernels/squeeze.d ./tflm/tensorflow/lite/micro/kernels/squeeze.o ./tflm/tensorflow/lite/micro/kernels/squeeze.su ./tflm/tensorflow/lite/micro/kernels/strided_slice.cyclo ./tflm/tensorflow/lite/micro/kernels/strided_slice.d ./tflm/tensorflow/lite/micro/kernels/strided_slice.o
	-$(RM) ./tflm/tensorflow/lite/micro/kernels/strided_slice.su ./tflm/tensorflow/lite/micro/kernels/strided_slice_common.cyclo ./tflm/tensorflow/lite/micro/kernels/strided_slice_common.d ./tflm/tensorflow/lite/micro/kernels/strided_slice_common.o ./tflm/tensorflow/lite/micro/kernels/strided_slice_common.su ./tflm/tensorflow/lite/micro/kernels/sub.cyclo ./tflm/tensorflow/lite/micro/kernels/sub.d ./tflm/tensorflow/lite/micro/kernels/sub.o ./tflm/tensorflow/lite/micro/kernels/sub.su ./tflm/tensorflow/lite/micro/kernels/sub_common.cyclo ./tflm/tensorflow/lite/micro/kernels/sub_common.d ./tflm/tensorflow/lite/micro/kernels/sub_common.o ./tflm/tensorflow/lite/micro/kernels/sub_common.su ./tflm/tensorflow/lite/micro/kernels/svdf_common.cyclo ./tflm/tensorflow/lite/micro/kernels/svdf_common.d ./tflm/tensorflow/lite/micro/kernels/svdf_common.o ./tflm/tensorflow/lite/micro/kernels/svdf_common.su ./tflm/tensorflow/lite/micro/kernels/tanh.cyclo ./tflm/tensorflow/lite/micro/kernels/tanh.d ./tflm/tensorflow/lite/micro/kernels/tanh.o ./tflm/tensorflow/lite/micro/kernels/tanh.su ./tflm/tensorflow/lite/micro/kernels/transpose.cyclo ./tflm/tensorflow/lite/micro/kernels/transpose.d ./tflm/tensorflow/lite/micro/kernels/transpose.o ./tflm/tensorflow/lite/micro/kernels/transpose.su ./tflm/tensorflow/lite/micro/kernels/unpack.cyclo ./tflm/tensorflow/lite/micro/kernels/unpack.d ./tflm/tensorflow/lite/micro/kernels/unpack.o ./tflm/tensorflow/lite/micro/kernels/unpack.su ./tflm/tensorflow/lite/micro/kernels/var_handle.cyclo ./tflm/tensorflow/lite/micro/kernels/var_handle.d ./tflm/tensorflow/lite/micro/kernels/var_handle.o ./tflm/tensorflow/lite/micro/kernels/var_handle.su ./tflm/tensorflow/lite/micro/kernels/while.cyclo ./tflm/tensorflow/lite/micro/kernels/while.d ./tflm/tensorflow/lite/micro/kernels/while.o ./tflm/tensorflow/lite/micro/kernels/while.su ./tflm/tensorflow/lite/micro/kernels/zeros_like.cyclo ./tflm/tensorflow/lite/micro/kernels/zeros_like.d ./tflm/tensorflow/lite/micro/kernels/zeros_like.o ./tflm/tensorflow/lite/micro/kernels/zeros_like.su

.PHONY: clean-tflm-2f-tensorflow-2f-lite-2f-micro-2f-kernels

